import type { OutputFormat } from "./gif-types";

export interface Project {
  id: string;
  name: string;
  sourceFile: { name: string; size: number; type: string };
  timeline: Timeline;
  outputSettings: OutputSettings;
  trimStart: number;
  trimEnd: number;
  /** Playback speed multiplier persisted with project (for example 0.5, 1, 1.5, 2). */
  playbackRate?: number;
  /** Optional user-saved text/sticker templates created from the current canvas overlays. */
  templates?: SavedTemplate[];
  /** Optional project restore points (named snapshots of editor state). */
  snapshots?: ProjectSnapshot[];
  createdAt: number;
  updatedAt: number;
}

export interface Timeline {
  duration: number;
  frameCount: number;
  overlays: Overlay[];
}

export interface SavedTemplate {
  id: string;
  name: string;
  description?: string;
  createdAt: number;
  updatedAt: number;
  previewDataUrl?: string;
  layers: SavedTemplateLayer[];
}

export interface SavedTemplateLayer {
  content: string;
  x: number;
  y: number;
  fontFamily?: string;
  fontWeight?: "normal" | "bold";
  fontStyle?: "normal" | "italic";
  textAlign?: "left" | "center" | "right";
  fontSize: number;
  color?: string;
  strokeWidth?: number;
  strokeColor?: string;
  effect?: AnimationPresetType;
}

export interface ProjectSnapshot {
  id: string;
  label: string;
  createdAt: number;
  state: ProjectSnapshotState;
}

export interface ProjectSnapshotState {
  overlays: Overlay[];
  outputSettings: OutputSettings;
  projectName: string;
  trimStart: number;
  trimEnd: number;
  playbackRate: number;
  currentFrameIndex: number;
}

export interface Overlay {
  id: string;
  type: "text" | "image";
  content: string;
  /** For image overlays: base64 data URL of the image */
  imageDataUrl?: string;
  /** For image overlays: natural width of the image in px */
  imageWidth?: number;
  /** For image overlays: natural height of the image in px */
  imageHeight?: number;
  fontFamily: string;
  fontSize: number;
  fontWeight: "normal" | "bold";
  fontStyle: "normal" | "italic";
  textAlign: "left" | "center" | "right";
  /** CSS unitless line-height multiplier. */
  lineHeight?: number;
  /** CSS letter spacing in pixels. */
  letterSpacing?: number;
  color: string;
  fillType?: "solid" | "gradient";
  gradientFrom?: string;
  gradientTo?: string;
  gradientAngle?: number;
  strokeWidth: number;
  strokeColor: string;
  textShadowColor?: string;
  textShadowBlur?: number;
  textShadowOffsetX?: number;
  textShadowOffsetY?: number;
  backgroundColor?: string;
  backgroundPaddingX?: number;
  backgroundPaddingY?: number;
  backgroundRadius?: number;
  keyframes: Keyframe[];
  effects: Effect[];
  /** Inclusive timeline start frame for overlay visibility. Default 0. */
  inFrame?: number;
  /** Inclusive timeline end frame for overlay visibility. Default last frame. */
  outFrame?: number;
  /** Optional group id for grouped timeline/canvas operations. */
  groupId?: string;
  /** Optional text transform for preview/export rendering. */
  textTransform?: "none" | "uppercase" | "lowercase";
  /** When false, layer is hidden on canvas and in export. Default true. */
  visible?: boolean;
  /** When true, layer edits/movement/removal are blocked until unlocked. */
  locked?: boolean;
  /** When true, keyframe interpolation is disabled (stepped motion). */
  disableTweening?: boolean;
  /** Name of the premium text preset applied. */
  textPreset?: string;
}

export interface Keyframe {
  frameIndex: number;
  x: number;
  y: number;
  scale: number;
  rotation: number;
  opacity: number;
  /** Easing to apply from this keyframe to the next. Default 'linear'. */
  easingToNext?: "linear" | "ease-in" | "ease-out" | "ease-in-out";
  /** True when this keyframe was auto-generated by tweening (not manually placed). */
  tweened?: boolean;
}

export interface Effect {
  type: AnimationPresetType;
  startFrame: number;
  endFrame: number;
  easing: "linear" | "ease-in" | "ease-out" | "ease-in-out";
  /** Typewriter cursor visual style. */
  cursorStyle?: TypewriterCursorStyle;
  /** Optional typewriter speed override in chars/second. */
  charsPerSecond?: number;
}

export type TypewriterCursorStyle = "bar" | "block" | "underscore";

export type AnimationPresetType =
  | "fade-in"
  | "fade-out"
  | "slide-up"
  | "slide-down"
  | "pop"
  | "scale-in"
  | "rotate-in"
  | "flicker"
  | "typewriter"
  | "bounce"
  | "shake"
  | "wiggle"
  | "pulse"
  | "neon-glow"
  | "glitch"
  | "rainbow";

export interface OutputSettings {
  width: number;
  height: number;
  format: OutputFormat;
  quality: number;
  crop?: CropRect | null;
  backgroundMode?: "transparent" | "solid";
  backgroundColor?: string;
}

export interface CropRect {
  /** Pixel x offset in source frame coordinates. */
  x: number;
  /** Pixel y offset in source frame coordinates. */
  y: number;
  /** Pixel crop width in source frame coordinates. */
  width: number;
  /** Pixel crop height in source frame coordinates. */
  height: number;
  /** Optional locked aspect ratio preset ("free", "1:1", "4:5", "16:9"). */
  aspectRatioPreset?: CropAspectPreset;
  /** Optional rotation in degrees for crop output intent (currently non-destructive). */
  rotation?: number;
  /** Optional horizontal flip intent for crop output (currently non-destructive). */
  flipX?: boolean;
  /** Optional vertical flip intent for crop output (currently non-destructive). */
  flipY?: boolean;
}

export type CropAspectPreset = "free" | "1:1" | "4:5" | "16:9";

export interface OverlayFrameRange {
  inFrame: number;
  outFrame: number;
}

export function clampOverlayFrameRange(
  inFrame: number,
  outFrame: number,
  frameCount: number
): OverlayFrameRange {
  const lastFrame = Math.max(0, frameCount - 1);
  const clampedIn = Math.max(0, Math.min(lastFrame, Math.round(inFrame)));
  const clampedOut = Math.max(clampedIn, Math.min(lastFrame, Math.round(outFrame)));
  return { inFrame: clampedIn, outFrame: clampedOut };
}

export function getOverlayFrameRange(
  overlay: Pick<Overlay, "inFrame" | "outFrame">,
  frameCount: number
): OverlayFrameRange {
  const lastFrame = Math.max(0, frameCount - 1);
  return clampOverlayFrameRange(overlay.inFrame ?? 0, overlay.outFrame ?? lastFrame, frameCount);
}

export function shiftOverlayFrameRange(
  range: OverlayFrameRange,
  frameDelta: number,
  frameCount: number
): OverlayFrameRange {
  const lastFrame = Math.max(0, frameCount - 1);
  if (lastFrame === 0 || frameDelta === 0) {
    return clampOverlayFrameRange(range.inFrame, range.outFrame, frameCount);
  }

  let nextIn = range.inFrame + frameDelta;
  let nextOut = range.outFrame + frameDelta;
  if (nextIn < 0) {
    nextOut += -nextIn;
    nextIn = 0;
  }
  if (nextOut > lastFrame) {
    const overflow = nextOut - lastFrame;
    nextIn -= overflow;
    nextOut = lastFrame;
  }
  return clampOverlayFrameRange(nextIn, nextOut, frameCount);
}

export function isFrameWithinOverlayRange(
  overlay: Pick<Overlay, "inFrame" | "outFrame">,
  frameIndex: number,
  frameCount: number
): boolean {
  const range = getOverlayFrameRange(overlay, frameCount);
  return frameIndex >= range.inFrame && frameIndex <= range.outFrame;
}
